# Generated by Django 4.1.3 on 2023-01-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='location',
            field=models.CharField(max_length=20, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Başlık'),
        ),
    ]
