# Generated by Django 4.1.3 on 2023-01-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_scheduling_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduling',
            old_name='title',
            new_name='name',
        ),
    ]
